spring:
  application:
    name: cloudalibaba-provider-cluster-payment
  datasource:
    username: root
    password: jliang83
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:13306/springcloud2021?useSSL=false
  cloud:
    nacos:
      config:
        server-addr=127.0.0.1:8848
      discovery:
        server-addr=127.0.0.1:8848
server:
  port: 9002
