spring:
  datasource:
    url: jdbc:mysql://localhost:13306/springcloud2021?useSSL=false
    username: root
    password: jliang83
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: cloud-consumer-feign-hystrix-order80
server:
  port: 80
eureka:
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 30
    instance-id: cloud-consumer-feign-hystrix-order80
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
    register-with-eureka: true
    fetch-registry: true
